# ─── 42_cli ───────────────────────────────────────────────────────────────────
NAME    := 42_cli

CXX     := g++
CXXFLAGS := -std=c++20 -Wall -Wextra -Werror -pedantic -O2
CXXFLAGS += -I./include
CXXFLAGS += -I./curl_dev_tmp/usr/include/x86_64-linux-gnu
CXXFLAGS += -MMD -MP

LDFLAGS := -L./curl_dev_tmp/usr/lib/x86_64-linux-gnu -lcurl -lncursesw -lpthread

PREFIX  ?= $(HOME)/.local
BINDIR  ?= $(PREFIX)/bin

SRC_DIR := src
OBJ_DIR := obj

SRCS := $(wildcard $(SRC_DIR)/*.cpp)
OBJS := $(patsubst $(SRC_DIR)/%.cpp, $(OBJ_DIR)/%.o, $(SRCS))

# ─── Default target ───────────────────────────────────────────────────────────
all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)
	@echo "Build successful → ./$(NAME)"

# ─── Compile objects ──────────────────────────────────────────────────────────
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp | $(OBJ_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

# ─── Install rule ─────────────────────────────────────────────────────────────
install: $(NAME)
	@mkdir -p $(DESTDIR)$(BINDIR)
	install -m 755 $(NAME) $(DESTDIR)$(BINDIR)/$(NAME)
	@echo "Installed $(NAME) to $(DESTDIR)$(BINDIR)/$(NAME)"

uninstall:
	rm -f $(DESTDIR)$(BINDIR)/$(NAME)
	@echo "Uninstalled $(NAME) from $(DESTDIR)$(BINDIR)/$(NAME)"

# ─── Standard rules ───────────────────────────────────────────────────────────
clean:
	rm -rf $(OBJ_DIR)

fclean: clean
	rm -f $(NAME)

re: fclean all

# Header dependencies generated by -MMD (rebuild objects when headers change).
-include $(OBJS:.o=.d)

.PHONY: all clean fclean re install uninstall
