# ─── 42_cli ───────────────────────────────────────────────────────────────────
NAME    := 42_cli

CXX     := g++
CXXFLAGS := -std=c++20 -Wall -Wextra -Werror -pedantic -O2
CXXFLAGS += -I./include
CXXFLAGS += -I./curl_dev_tmp/usr/include/x86_64-linux-gnu
CXXFLAGS += -MMD -MP

LDFLAGS := -L./curl_dev_tmp/usr/lib/x86_64-linux-gnu -lcurl -lncursesw -lpthread

PREFIX  ?= $(HOME)/.local
BINDIR  ?= $(PREFIX)/bin

SRC_DIR := src
OBJ_DIR := obj

SRCS := $(wildcard $(SRC_DIR)/*.cpp)
OBJS := $(patsubst $(SRC_DIR)/%.cpp, $(OBJ_DIR)/%.o, $(SRCS))

# ─── Default target ───────────────────────────────────────────────────────────
all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)
	@echo "Build successful → ./$(NAME)"

# ─── Compile objects ──────────────────────────────────────────────────────────
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp | $(OBJ_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

# ─── Install rule ─────────────────────────────────────────────────────────────
install: $(NAME)
	@mkdir -p $(DESTDIR)$(BINDIR)
	install -m 755 $(NAME) $(DESTDIR)$(BINDIR)/$(NAME)
	@echo "Installed $(NAME) to $(DESTDIR)$(BINDIR)/$(NAME)"

uninstall:
	rm -f $(DESTDIR)$(BINDIR)/$(NAME)
	@echo "Uninstalled $(NAME) from $(DESTDIR)$(BINDIR)/$(NAME)"

# ─── Update: backup local work, pull, full rebuild, install and launch ───────
# Terminal used to open the TUI in the background (new window). Override with
#   make update UPDATE_TERMINAL=kitty UPDATE_LAUNCH=-e
UPDATE_TERMINAL ?= $(shell command -v ghostty 2>/dev/null || command -v kitty 2>/dev/null || command -v wezterm 2>/dev/null || command -v x-terminal-emulator 2>/dev/null || true)
UPDATE_LAUNCH   ?= -e

update:
	@git fetch origin || exit 1; \
	if [ -n "$$(git status --porcelain)" ] || [ -n "$$(git rev-list origin/main..HEAD 2>/dev/null)" ]; then \
		backup="masterbak"; \
		if git show-ref --verify --quiet refs/heads/masterbak; then \
			printf "Ya existe la rama 'masterbak'. ¿Sobrescribir (s) o conservar respaldo (c)? [s/c]: "; \
			read ans || ans=s; \
			case "$$ans" in c|C) backup="masterbak-$$(date +%Y%m%d-%H%M%S)";; *) backup="masterbak";; esac; \
		fi; \
		echo "==> Guardando cambios locales en '$$backup'..."; \
		git checkout -B "$$backup"; \
		git add -A; \
		git commit -m "backup: local changes before make update" || true; \
		git checkout main; \
		git reset --hard origin/main; \
	fi; \
	git pull --ff-only
	@$(MAKE) --no-print-directory fclean
	@$(MAKE) --no-print-directory install
	@echo "==> Abriendo $(NAME) en segundo plano..."
	@if [ -n "$(UPDATE_TERMINAL)" ]; then \
		setsid "$(UPDATE_TERMINAL)" $(UPDATE_LAUNCH) $(NAME) >/dev/null 2>&1 & \
	else \
		setsid $(NAME) >/dev/null 2>&1 & \
	fi

run: $(NAME)
	@if [ -n "$(UPDATE_TERMINAL)" ]; then \
		setsid "$(UPDATE_TERMINAL)" $(UPDATE_LAUNCH) $(NAME) >/dev/null 2>&1 & \
	else \
		setsid $(NAME) >/dev/null 2>&1 & \
	fi

# ─── Standard rules ───────────────────────────────────────────────────────────
clean:
	rm -rf $(OBJ_DIR)

fclean: clean
	rm -f $(NAME)

re: fclean all

# Header dependencies generated by -MMD (rebuild objects when headers change).
-include $(OBJS:.o=.d)

.PHONY: all clean fclean re install uninstall update run
